### ISSUE TITLE
Random SASS Style Guide ideas.

### ISSUE THREAD

**Issue by eriku** [domain7/dev-wiki#4]
I really like Chris Coyier's style guide (http://css-tricks.com/sass-style-guide). A few that I would like to see implemented "officially".

We can separate these into separate issues if need be. Just thought I'd throw them all in for now.
- I'm not sold on his @extend first, regular styles second and @includes last. I personally like what we have, @extend, @include then regular styles. But I would like to suggest sorting alphabetically instead of by [_type_](http://domain7.github.io/fed-wiki/css/#sass-style-guide_rule-order). I'm not sure about y'all but i can find styles easier when they are in a standard order (alphabetical / numerical).
- If you need to use vender prefixes, it should be in a @mixin.
- Maximum nesting levels should be 3 levels deep & maximum of 50 lines
- **_Maybe_** implement a "_shame.scss" partial. Although when building this file should never be used. (http://csswizardry.com/2013/04/shame-css)

**Comment by nathansh** [comment]
This is a great article and I definitely referenced it when writing my draft. A couple things:
- If you need a vendor prefix, you should use Compass. Compass covers all vendor prefixes you'll need (I'm pretty sure). We shouldn't be using libraries other than Compass if Compass has the feature we want. If there's something missing, then for sure make a mixin (maybe make a pull request with it if you find something missing).
- I definitely appreciate Chris Coyier's "3 levels deep rule", and I think it's a good starting place, but I definitely disagree that 4 levels deep is by definition bad practice. I think this needs to be a case by case basis where good judgment prevails, but where we avoid unnecessary nesting. Sometimes it'd actually be _better_ to nest 4 levels if this enhances clarity. For example, say you have a flexslider. You have some markup with that which just might require a 4th level, and it'd be easier to maintain should it all be contained. I wouldn't be surprised if flexslider was an actual case where you'd need another level. So, I think this can be dealt with using good judgment and a concerted effort to keep nesting shallow but readable/logical.
- Same note about the 50 line rule. That's totally arbitrary. Say you need a lot of IE fallback stuff in a CSS3 heavy declaration block. Nesting this stuff I think is good practice for encapsulation and readability, but might push you to 100 lines. And that might be a good thing because the encapsulation could outweigh the length.
- I feel _reeeaaaaalllyy_ strongly against including a _shame.scss file. If you use it, you know you're doing something you shouldn't. So just don't. If you can't get away from it though, then create it on an as needed basis but if we include it in the boilerplate we're encouraging it.

**Comment by nathansh** [comment]
About sorting declaration blocks by type vs alphabetically, in all case of sorting, the key should be the thing you're referencing _against_. So alphabetical sorting is effective with a phone book because you're looking for a name. But with CSS, the name of the rule is secondary to what you're trying to achieve. You can prove this by verbally describing something like a header style. "This header is going to be centred on the page with 1 em of spacing above and below, and it'll be 32px, all caps, in orange." In general what gives your code logical order is grouping by functionality, not necessarily by name.

**Comment by eriku** [comment]
Maybe I wasn't to clear or maybe our wiki isn't clear. I didn't mean declaration blocks, I meant styles.

``` sass
// Good
body {
  background: #ccc;
  font-family: verdana;
  left: 25%;
  margin: 0;
  min-width: 230px;
  padding-top: 30px;
  position: absolute;
  top: 20px;
}

// Bad
body {
  position: absolute;
  top: 20px;
  left: 25%;
  background: #ccc;
  padding-top: 30px;
  margin: 0;
  min-width: 230px;
  font-family: verdana;
}
```

**Comment by eriku** [comment]
Also, we are creating guidelines. As of right now there is no _rule_ (use rule loosely) on nesting levels other than **"Only nest as much as you need to and as little as you can get away with."**. I think the wording should be stronger.

**Comment by nathansh** [comment]
@eriku Your explanation definitely was clear and the example clarifies it. I just don't agree at all. I think rules should be grouped by functionality since functionality is a reference point whereas the first letter doesn't provide much value.

**Comment by reubenmoes** [comment]
I would vote for @extend then @mixin then styles.  

I'm not a fan of a hard rule agains nesting levels or max lines.  I think it can be a guideline, but not absolute.  As long as it is clear that it is not necessary for the CSS selectors to match the DOM structure.  

I've always organized by type.  Usually  by positioning & size, margins + padding, colors, fonts (but I don't really care too much about that order).   I find having things closely related to things that they are similar to is much easier for development.  Often if you are adjusting the margin, you may need to adjust the padding.  If you adjust the background, you might need to adjust the color.  If you are adjusting the position:absolute, you probably need to set the top/left/bottom/right.  If you are adjusting the font size, you might need to adjust the line-height.   I like this logic: http://youtu.be/vb60rrtTddQ?t=9m1s

**Comment by eriku** [comment]
@nathanshubert & @reubenmoes : I **REALLY** don't agree... I think more about the time spent searching for what I need to change and his comment [here](http://youtu.be/vb60rrtTddQ?t=9m47s) says exactly how I feel. So his logic only "sorta works". It's automatic for me to visually search the whole section anyway whether it's by type/category or alphabetical, but I find what I'm looking for quicker if it's alphabetical.

Maybe that's the difference... Development vs Support.

When it comes to handing our projects over to support / the client we need to think about what is easier for them instead of what is easier for us seeing how the development is the shorter of the two in the long run.

**Comment by reubenmoes** [comment]
Just throwing this out there.  This might be helpful for cleaning up and/or reordering SASS, whichever method we choose.
http://csscomb.com/

I think we should also add some Grunt Sass linting to make our code more consistent across the team. 

For the ordering issue.  i just think it would be so odd splitting up something like: 

```
position: absolute
top: 50px;
right: 50px;
```

Often you want your line-height to match the height of the element so the text is vertically centered.  If you were to reorganize a long list of style properties, you would most likely lose the context that the text is supposed to be vertically aligned.  Someone coming in after and changing the height of the element, might not clue in that the line-height matches the height of the element.

```
height: 100px
line-height: 100px;
```

**Comment by nathansh** [comment]
Yeah, exactly. @reubenmoes's examples are really good. When you're writing css, you're grouping your rules together in accordance with how you think through the problem, not in terms of the alphabet. Alphabetizing your rules would involve another step. So it makes most sense to write them that way. But even for support, @reubenmoes's point about context is also really great, and you'd loose it for alphabetical sorting. Unless you have 30 rules, I don't think it'd be difficult to find the rule you need with functional grouping.

**Comment by eriku** [comment]
I still disagree but I'll go with whatever the majority agrees on.

**Comment by nathansh** [comment]
In general, I think grouping by function is a logical grouping that has inherent value to how CSS is written, while alphabetization seems fairly arbitrary.

**Comment by lancejanocha** [comment]
Logical grouping for me.

I think consistency is more important though - perhaps this doesn't have to be a steadfast rule? 90% of selectors are pretty simple < 10 lines, and the ordering will be apparent. If the entire site is built with a consistent rule order, navigating the stylesheets won't be an issue.

**Comment by reubenmoes** [comment]
Is anybody interested in setting a standard ordering function groups?  It might be good to have a loose standard, but not absolute.  

```
//mixins
transition,animation,border-radius,shadow,etc
//Position
display,position,top,left,bottom,right
//Size + 
width,height,margin,padding,border
//type
font-family,font-size,font-weight,color
//other stuff
```

I'd prefer if it was more of a recommendation and not absolute, as I wouldn't want it to control the thinking around solving CSS problems.  For example, even the standard above would not allow something like the vertical centering solution below:

```
height: 100px
line-height: 100px; 
```

**Comment by nathansh** [comment]
That's great, I +1 that @reubenmoes. The most common approach to this seems to be working with the boxmodel, working outwards in, which this is inline with. So, display: block; for instance would come before margins, which come before font sizing. And I agree 100 percent with using it as a guideline but letting logical judgment overwrite for cases like your vertical centring example.

**Comment by eriku** [comment]
Are we planning on using something like scss-lint, which I'd love to start doing so that everything is truely consistent. I know you can customize the order manually but here's their default concentric order - https://github.com/causes/scss-lint/blob/master/data/property-sort-orders/concentric.txt

**Comment by reubenmoes** [comment]
+1 scss-lint . Looks like there are a few options for us to use (editor integration, git hooks, grunt task)

**Comment by nathansh** [comment]
Yup. I think JS linting and markup validation are bigger fish to fry though. With markup validation, it's not super important that it validate in the green checkmark sense, but more in the "no improper nesting of elements, no unclosed elements" sense.

**Comment by reubenmoes** [comment]
jshint is in the [gruntyplate](https://bitbucket.org/domain7/gruntyplate/src/687d0d24ae779eb130b00e98a7d2f73ca4a33962/Gruntfile.js?at=master#cl-49)

I don't see any harm in running scss-lint.  And definitely markup validation is a big thing.  Personally I use  [syntastic](https://github.com/scrooloose/syntastic) this for vim:  and [validity](https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif?hl=en-GB) for chrome.

There might be some similar plugins for sublime.

**Comment by eriku** [comment]
[SublimeLinter](http://www.sublimelinter.com/en/latest/) Only for SublimeText 3 though

**Comment by reubenmoes** [comment]
I tried the scss-lint a bit.  The default state seems like a bit overkill.  If we use it, we might need to narrow down the scope to things we only really care about.

**Comment by eriku** [comment]
Yup, I definitely agree @reubenmoes. I was just running through their Linters - https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

**Comment by nathansh** [comment]
Oh yeah, you gotta tone scss-lint RIGHT down.

**Comment by reubenmoes** [comment]
I see some real benefit in having SCSS-lint on all projects with a standard config that we use all around.  It would help warn you early on about a lot of the things that we have been discussing and are in the fed-wiki already.  Things like: 
- Ensuring separate selectors are on their own line
- make sure @extend @mixin  are at the top
- Nesting level
- property order

But also
- Duplicate properties (putting float:left; float:right in the same rule)
- Space before { 
  -other stuffs

[Screenshot of my editor after saving file](https://www.dropbox.com/s/s15rzir43amyr5b/Screenshot%202014-11-26%2017.57.24.png?dl=0)

If anyone wants to play around with it, here was my .scss-config.yml 

```

scss_files: 'stylesheets/scss/**/*.scss'

linters:
  BorderZero:
    enabled: false

  Indentation:
    enabled: false

  StringQuotes:
    enabled: false

  Comment:
    enabled: false

  EmptyLineBetweenBlocks:
    enabled: false

  PropertySortOrder:
    enabled: false

  VendorPrefixes:
    enabled: false

```

**Comment by reubenmoes** [comment]
If you're down with SCSS-Lint.  I just added an [ issue in sassyplate](https://bitbucket.org/domain7/sassyplate/issue/3/add-scss-configyml-file)

**Comment by eriku** [comment]
Ordering declarations: At least I think like google :) http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml?showone=Declaration_Order#Declaration_Order

**Comment by nathansh** [comment]
Unless I'm missing something:

Reasons to sort alphabetically:
- Looks pretty
- Easy to index by alphabetical key, which could be useful with extremely large blocks

Reasons to sort by function:
- Easier to write (write all related blocks as you think through the issue)
- Preserve context between related rules (Reuben had a good example of this)
- Easier to find rules in practice since anything pertaining to text is grouped, likewise positioning and the box model

Also, right now we have for logical grouping: Rueben, Lance, Nathan. For alphabetical: Erik. Undeclared: Jamie and Miriam. So, the best alphabetical sorting can hope for is a tie, but I'll sooner buy @verticalgrain's vote with brownies, so...

**Comment by nathansh** [comment]
I think though, possibly the best reason we shouldn't order declarations alphabetically is the workflow. You're going to write CSS in logical order, as you think through what you need to accomplish, then you're going to have to circle back and re-order your declarations alphabetically. Because, you're _definitely_ not going to think "I'm going to write position, but first I'll write my font-weight because F comes before P in the alphabet." So we'd be adding an extra step which will add up really quickly for debatable gain.

**Comment by andmiriam** [comment]
+1 for logical grouping over alphabetical. For all the reasons already stated here.

**Comment by nathansh** [comment]
![match](http://media.giphy.com/media/4lf1bJCHHGKdy/giphy.gif)

**Comment by eriku** [comment]
Still disagree but as previously stated... i will go with majority rule

**Comment by nathansh** [comment]
The team has concluded that it favours logical ordering of rules over alphabetical ordering.
